#!/usr/bin/env python
"""
Baxter RSDK Gripper Example: keyboard
"""
import roslib
roslib.load_manifest('gripper_control')
import rospy

import baxter_interface
import iodevices


from baxter_interface import Gripper

def map_keyboard():
    left = baxter_interface.Gripper('left')
    right = baxter_interface.Gripper('right')
    bindings = {
    #   key: (function, args, description)
        'r': (left.reboot, [], "left: reboot"),
        'R': (right.reboot, [], "right: reboot"),
        'c': (left.calibrate, [], "left: calibrate"),
        'C': (right.calibrate, [], "right: calibrate"),
        'q': (left.close, [], "left: close"),
        'Q': (right.close, [], "right: close"),
        'w': (left.open, [], "left: open"),
        'W': (right.open, [], "right: open"),
        '[': (left.set_velocity, [100.0], "left: set 100% velocity"),
        '{': (right.set_velocity, [100.0], "right: set 100% velocity"),
        ']': (left.set_velocity, [30.0], "left: set 30% velocity"),
        '}': (right.set_velocity, [30.0], "right: set 30% velocity"),
        's': (left.stop, [], "left: stop"),
        'S': (right.stop, [], "right: stop"),
        'z': (left.inc_dead_band, [-1.0], "left: decrease dead band"),
        'Z': (right.inc_dead_band, [-1.0], "right: decrease dead band"),
        'x': (left.inc_dead_band, [1.0], "left: increase dead band"),
        'X': (right.inc_dead_band, [1.0], "right: increase dead band"),
        'f': (left.inc_force, [-5.0], "left: decrease moving force"),
        'F': (right.inc_force, [-5.0], "right:  decrease moving force"),
        'g': (left.inc_force, [5.0], "left:  increase moving force"),
        'G': (right.inc_force, [5.0], "right:  increase moving force"),
        'h': (left.inc_holding_force, [-5.0], "left:  decrease holding force"),
        'H': (right.inc_holding_force, [-5.0], "right:  decrease holding force"),
        'j': (left.inc_holding_force, [5.0], "left:  increase holding force"),
        'J': (right.inc_holding_force, [5.0], "right:  increase holding force"),
        'v': (left.inc_velocity, [-5.0], "left:  decrease velocity"),
        'V': (right.inc_velocity, [-5.0], "right:  decrease velocity"),
        'b': (left.inc_velocity, [5.0], "left:  increase velocity"),
        'B': (right.inc_velocity, [5.0], "right:  increase velocity"),
        'u': (left.inc_position, [-5.0], "left:  decrease position"),
        'U': (right.inc_position, [-5.0], "right:  decrease position"),
        'i': (left.inc_position, [5.0], "left:  increase position"),
        'I': (right.inc_position, [5.0], "right:  increase position"),
    }
    done = False
    while not done:
        c = iodevices.getch()
        if c:
            if c in ['\x1b']:
                done = True
            elif c in bindings:
                cmd = bindings[c]
                cmd[0](*cmd[1])
                print("command: %s" % (cmd[2],))
            else:
                print("key bindings: ")
                print("  Esc: Quit")
                for key, val in sorted(bindings.items(), key=lambda x: x[1][2]):
                    print("  %s: %s" % (key, val[2]))


def main():
    print("Initializing node... ")
    rospy.init_node("rethink_rsdk_gripper_keyboard")
    print("Getting robot state... ")
    rs = baxter_interface.RobotEnable()
    print("Enabling robot... ")
    rs.enable()

    map_keyboard()

    print("Disabling robot... ")
    rs.disable()

if __name__ == '__main__':
    main()
