#!/usr/bin/env python
import roslib
roslib.load_manifest('joint_position')
import rospy
import baxter_interface

from controllers import JointPositionBaxterController
from mappers import KeyboardMapper

if __name__ == '__main__':
    print("Initializing node... ")
    rospy.init_node("rethink_rsdk_joint_position_keyboard")
    print("Getting robot state... ")
    rs = baxter_interface.RobotEnable()
    print("Enabling robot... ")
    rs.enable()

    mapper = KeyboardMapper(JointPositionBaxterController())

    mapper.loop()
    rs.disable()
