#!/usr/bin/env python
import argparse

import roslib
roslib.load_manifest('joint_position')
import rospy

from recorders import SparseRecorder

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument("filename", help="the file name to record to")
  parser.add_argument("-r", "--record-rate", dest="recordRate", type=int, default=100, help="rate at which to record")
  parser.add_argument("-d", "--joint-delta", dest="jointDelta", type=float, default=0.1, help="joint delta to trigger recording a frame")
  args = parser.parse_args()

  print("Initializing node... ")
  rospy.init_node("rethink_rsdk_joint_recorder")
  recorder = SparseRecorder(args.filename, args.recordRate, args.jointDelta)
  print("recording...")
  recorder.record()
  print("done.")
