#!/usr/bin/env python
import argparse

import roslib
roslib.load_manifest('joint_pose')
import rospy
import enable_robot

from controllers import JointPositionBaxterController
from mappers import JoystickMapper

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument("joystick", help="specify the type of joystick to use; xbox or logitech")
  args, unknown = parser.parse_known_args()

  print("Initializing node... ")
  rospy.init_node("rethink_rsdk_joint_pose_joystick")
  print("Getting robot state... ")
  rs = enable_robot.RobotState()
  print("Enabling robot... ")
  rs.enable()

  if args.joystick in ['xbox', 'logitech']:
    mapper = JoystickMapper(JointPositionBaxterController(), args.joystick)
  else:
    parser.error("Unsupported joystick type '%s'" % (args.joystick))

  mapper.loop()
  rs.disable()
