#!/usr/bin/env python
import roslib
roslib.load_manifest('joint_pose')
import rospy
import enable_robot

from controllers import JointPositionBaxterController
from mappers import KeyboardMapper

if __name__ == '__main__':
    print("Initializing node... ")
    rospy.init_node("rethink_rsdk_joint_pose_keyboard")
    print("Getting robot state... ")
    rs = enable_robot.RobotState()
    print("Enabling robot... ")
    rs.enable()

    mapper = KeyboardMapper(JointPositionBaxterController())

    mapper.loop()
    rs.disable()
